version: "3"
services:
  db:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  test-db:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${TEST_DATABASE_USER}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD}
      POSTGRES_DB: ${TEST_DATABASE_NAME}
  broker-db:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5434:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${BROKER_DATABASE_USER}
      POSTGRES_PASSWORD: ${BROKER_DATABASE_PASSWORD}
      POSTGRES_DB: ${BROKER_DATABASE_NAME}
  pact-broker:
    image: pactfoundation/pact-broker
    links:
      - broker-db
    ports:
      - 8000:9292
    env_file:
      - ./.env
    environment:
      PACT_BROKER_BASIC_AUTH_USERNAME: ${PACT_BROKER_USERNAME}
      PACT_BROKER_BASIC_AUTH_PASSWORD: ${PACT_BROKER_PASSWORD}
      PACT_BROKER_DATABASE_USERNAME: ${BROKER_DATABASE_USER}
      PACT_BROKER_DATABASE_PASSWORD: ${BROKER_DATABASE_PASSWORD}
      PACT_BROKER_DATABASE_HOST: broker-db
      PACT_BROKER_DATABASE_NAME: ${BROKER_DATABASE_NAME}
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "10"
